#!/usr/bin/env bash
#
# Maker installer — macOS / Linux.
# Sets up a `maker` command that runs the app from this cloned repo. It creates
# exactly one small file outside the repo: a launcher in your bin dir. No system
# directories are touched. Models/tools/memory only ever live under MAKER_HOME
# (default ~/.maker), created on first /setup.
#
# Usage:   bash scripts/install.sh
# Env:     MAKER_BIN_DIR (default ~/.local/bin), MAKER_HOME (default ~/.maker)
#
set -euo pipefail

REPO_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
BIN_DIR="${MAKER_BIN_DIR:-$HOME/.local/bin}"
MAKER_HOME="${MAKER_HOME:-$HOME/.maker}"
LAUNCHER="$BIN_DIR/maker"

echo "Maker installer"
echo "  repo:      $REPO_DIR"
echo "  launcher:  $LAUNCHER"
echo "  app data:  $MAKER_HOME (created on first /setup)"
echo

# 1) Node check (Maker runs the TypeScript sources natively).
if ! command -v node >/dev/null 2>&1; then
  echo "✗ Node.js not found. Install Node >= 23.6 (Node 26 recommended): https://nodejs.org"
  exit 1
fi
NODE_MAJOR="$(node -p 'process.versions.node.split(".")[0]')"
if [ "$NODE_MAJOR" -lt 23 ]; then
  echo "✗ Node $(node -v) is too old — Maker needs Node >= 23.6."
  exit 1
fi
echo "✓ Node $(node -v)"

# 2) Install the launcher.
mkdir -p "$BIN_DIR"
cat > "$LAUNCHER" <<EOF
#!/usr/bin/env bash
# Maker launcher — generated by install.sh. Delete via scripts/uninstall.sh.
REPO="$REPO_DIR"
case "\${1:-gui}" in
  gui)            exec node "\$REPO/packages/gui/serve.ts" ;;
  tui)            exec node "\$REPO/packages/tui/src/repl.ts" ;;
  -h|--help|help) echo "usage: maker [gui|tui]" ;;
  *)              echo "unknown command: \$1"; echo "usage: maker [gui|tui]"; exit 1 ;;
esac
EOF
chmod +x "$LAUNCHER"
echo "✓ Installed launcher"

# 3) PATH hint.
case ":$PATH:" in
  *":$BIN_DIR:"*) : ;;
  *)
    echo
    echo "⚠ $BIN_DIR is not on your PATH. Add it, e.g.:"
    echo "    echo 'export PATH=\"$BIN_DIR:\$PATH\"' >> ~/.zshrc && source ~/.zshrc"
    ;;
esac

echo
echo "Done. Start Maker:"
echo "    maker        # GUI in your browser"
echo "    maker tui    # terminal"
echo "Then type /setup to download a model."
echo
echo "To remove Maker completely later:  bash $REPO_DIR/scripts/uninstall.sh"
