# Maker installer — Windows (PowerShell).
# Sets up a `maker` command that runs the app from this cloned repo. Creates one
# launcher file under %LOCALAPPDATA%\Maker\bin. Models/tools/memory live only
# under MAKER_HOME (default %USERPROFILE%\.maker), created on first /setup.
#
# Usage:  powershell -ExecutionPolicy Bypass -File scripts\install.ps1
# Env:    MAKER_BIN_DIR (default %LOCALAPPDATA%\Maker\bin), MAKER_HOME (default %USERPROFILE%\.maker)

$ErrorActionPreference = "Stop"

$RepoDir   = (Resolve-Path (Join-Path $PSScriptRoot "..")).Path
$BinDir    = if ($env:MAKER_BIN_DIR) { $env:MAKER_BIN_DIR } else { Join-Path $env:LOCALAPPDATA "Maker\bin" }
$MakerHome = if ($env:MAKER_HOME)    { $env:MAKER_HOME }    else { Join-Path $env:USERPROFILE ".maker" }
$Launcher  = Join-Path $BinDir "maker.cmd"

Write-Host "Maker installer"
Write-Host "  repo:     $RepoDir"
Write-Host "  launcher: $Launcher"
Write-Host "  app data: $MakerHome (created on first /setup)"
Write-Host ""

# 1) Node check
if (-not (Get-Command node -ErrorAction SilentlyContinue)) {
  Write-Error "Node.js not found. Install Node >= 23.6 (Node 26 recommended): https://nodejs.org"
  exit 1
}
$major = [int](node -p "process.versions.node.split('.')[0]")
if ($major -lt 23) { Write-Error "Node $(node -v) is too old — Maker needs Node >= 23.6."; exit 1 }
Write-Host "OK  Node $(node -v)"

# 2) Install the launcher (a .cmd shim)
New-Item -ItemType Directory -Force -Path $BinDir | Out-Null
$cmd = @"
@echo off
REM Maker launcher — generated by install.ps1. Delete via scripts\uninstall.ps1.
set "REPO=$RepoDir"
if "%~1"=="tui" ( node "%REPO%\packages\tui\src\repl.ts" %* & goto :eof )
if "%~1"=="-h"  ( echo usage: maker [gui^|tui] & goto :eof )
node "%REPO%\packages\gui\serve.ts"
"@
Set-Content -Path $Launcher -Value $cmd -Encoding ASCII
Write-Host "OK  Installed launcher"

# 3) PATH hint
if (($env:Path -split ';') -notcontains $BinDir) {
  Write-Host ""
  Write-Host "WARN  $BinDir is not on your PATH. Add it (user scope):"
  Write-Host "      setx PATH `"$BinDir;%PATH%`""
}

Write-Host ""
Write-Host "Done. Start Maker:"
Write-Host "    maker        # GUI in your browser"
Write-Host "    maker tui    # terminal"
Write-Host "Then type /setup to download a model."
Write-Host ""
Write-Host "To remove Maker completely later:  powershell -File `"$RepoDir\scripts\uninstall.ps1`""
