# Maker installer — Windows (PowerShell).
# Sets up a `maker` command that runs the app from this cloned repo. Creates one
# launcher file under %LOCALAPPDATA%\Maker\bin. Models/tools/memory live only
# under MAKER_HOME (default %USERPROFILE%\.maker), created on first /setup.
#
# Usage:  powershell -ExecutionPolicy Bypass -File scripts\install.ps1
# Env:    MAKER_BIN_DIR (default %LOCALAPPDATA%\Maker\bin), MAKER_HOME (default %USERPROFILE%\.maker)

$ErrorActionPreference = "Stop"

$RepoDir   = (Resolve-Path (Join-Path $PSScriptRoot "..")).Path
$BinDir    = if ($env:MAKER_BIN_DIR) { $env:MAKER_BIN_DIR } else { Join-Path $env:LOCALAPPDATA "Maker\bin" }
$MakerHome = if ($env:MAKER_HOME)    { $env:MAKER_HOME }    else { Join-Path $env:USERPROFILE ".maker" }
$Launcher  = Join-Path $BinDir "maker.cmd"

Write-Host "Maker installer"
Write-Host "  repo:     $RepoDir"
Write-Host "  launcher: $Launcher"
Write-Host "  app data: $MakerHome (created on first /setup)"
Write-Host ""

# 1) Node check
if (-not (Get-Command node -ErrorAction SilentlyContinue)) {
  Write-Error "Node.js not found. Install Node >= 23.6 (Node 26 recommended): https://nodejs.org"
  exit 1
}
$major = [int](node -p "process.versions.node.split('.')[0]")
if ($major -lt 23) { Write-Error "Node $(node -v) is too old — Maker needs Node >= 23.6."; exit 1 }
Write-Host "OK  Node $(node -v)"

# 2) Install the launcher (a .cmd shim)
New-Item -ItemType Directory -Force -Path $BinDir | Out-Null
$cmd = @"
@echo off
REM Maker launcher — generated by install.ps1. Delete via scripts\uninstall.ps1.
set "REPO=$RepoDir"
if "%~1"=="tui"   ( node "%REPO%\packages\tui\src\repl.ts" %* & goto :eof )
if "%~1"=="serve" ( shift & node "%REPO%\packages\gui\serve.ts" %* & goto :eof )
if "%~1"=="setup"  ( node "%REPO%\packages\tui\src\setup.ts" & goto :eof )
if "%~1"=="doctor" ( node "%REPO%\packages\tui\src\doctor.ts" & goto :eof )
if "%~1"=="-h"     ( echo usage: maker [gui^|serve^|tui^|setup^|doctor] & goto :eof )
node "%REPO%\packages\gui\serve.ts"
"@
Set-Content -Path $Launcher -Value $cmd -Encoding ASCII
Write-Host "OK  Installed launcher"

# 2b) Start Menu shortcut — a clickable app icon.
$StartMenu = Join-Path $env:APPDATA "Microsoft\Windows\Start Menu\Programs"
$Shortcut  = Join-Path $StartMenu "Maker.lnk"
try {
  $ws = New-Object -ComObject WScript.Shell
  $sc = $ws.CreateShortcut($Shortcut)
  $sc.TargetPath   = $Launcher
  $sc.Arguments    = "gui"
  $sc.Description   = "Build tools by conversation — on-device, offline"
  $sc.WorkingDirectory = $RepoDir
  $sc.Save()
  Write-Host "OK  Installed Start Menu shortcut (search 'Maker')"
} catch {
  Write-Host "WARN  Could not create Start Menu shortcut (non-fatal)"
}

# 3) PATH hint
if (($env:Path -split ';') -notcontains $BinDir) {
  Write-Host ""
  Write-Host "WARN  $BinDir is not on your PATH. Add it (user scope):"
  Write-Host "      setx PATH `"$BinDir;%PATH%`""
}

# 4) Offer to download a model now.
$doSetup = Read-Host "Download a model now so Maker is ready to build? (needs internet) [Y/n]"
if ($doSetup -notmatch '^(n|no)$') {
  Write-Host ""
  node "$RepoDir\packages\tui\src\setup.ts"
}

Write-Host ""
Write-Host "Done. Start Maker:"
Write-Host "    * App icon:  search 'Maker' in the Start Menu (double-click)"
Write-Host "    * Command:   maker        (GUI)   ·   maker tui   (terminal)"
Write-Host "    * Model:     maker setup  (download a model, if you skipped it above)"
Write-Host ""
Write-Host "To remove Maker completely later:  powershell -File `"$RepoDir\scripts\uninstall.ps1`""
